language: android
sudo: required
jdk: oraclejdk8

env:
 global:
 - ANDROID_API=33
 - EMULATOR_API=24
 - ANDROID_BUILD_TOOLS=33.0.1
 - ADB_INSTALL_TIMEOUT=5 # minutes

android:
 components:
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS
 - android-$ANDROID_API
 - android-$EMULATOR_API_LEVEL
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 - addon-google_apis-google-19 # google play services
 - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
 - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
 licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+

before_install:
- echo y | android update sdk --no-ui --all --filter "tools,build-tools-33.0.1,platform-tools,android-33,extra-android-m2repository,extra-google-m2repository"
- yes | sdkmanager "platforms;android-33"
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
- chmod +x gradlew

script:
- "./gradlew assembleRelease -PXIL_RELEASE_STORE_FILE=keystore/keystore.jks -PXIL_RELEASE_STORE_PASSWORD=$XIL_RELEASE_STORE_PASSWORD -PXIL_RELEASE_KEY_ALIAS=key0 -PXIL_RELEASE_KEY_PASSWORD=$XIL_RELEASE_KEY_PASSWORD"
- curl -s -F secret=$CURL_SECRET -F public=true -F userfile=@./app/build/outputs/apk/release/app-release.apk $CURL_URL

